# add test later

stages:
  - deploy

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME_IVORY
    TWINE_PASSWORD: $PYPI_PASSWORD_IVORY
  image: python:3.10-slim
  before_script:
    - pip install build twine
  script:
    - python -m build
    - twine upload --non-interactive dist/*
  only:
    - tags